### ISSUE TITLE
EPG予約でワンセグが選択されない

### ISSUE THREAD

**Issue by 5ym** [EMWUI/EDCB_Material_WebUI#1]
EPG予約でワンセグにチェック保存しても再度開くとワンセグのチェックが外れておりepgtimerで確認するとワンセグチャンネルのチェックがはずれている

**Comment by EMWUI** [comment]
EPG予約のサービス絞り込みにある、映像のみや地上波などのチェックボックスは直上のチャンネルリストを表示・非表示するための補助機能でEPG予約の設定には関係ありません
なのでワンセグを対象にしたい場合はワンセグにチェック入れ表示した後、上のリストで選択してください
またワンセグだけにしたい場合などはワンセグのみにチャックを入れ全選択をクリックするとワンセグのみ選択することができます

**Comment by 5ym** [comment]
ワンセグにチェックを入れた際上のチャンネルリストに表示されません

**Comment by EMWUI** [comment]
こちらでは再現できません
ワンセグのチャンネルをEPGデータ取得対象にしてるでしょうか？
epgCapFlag(EPGデータ取得対象かどうか)があるのみリストアップしてます

**Comment by 5ym** [comment]
すみませんこちらのミスでした取得対象にチェックを入れたところ表示されました。番組表の方はチェックを入れなくても表示される仕様という認識でよろしいでしょうか

**Comment by EMWUI** [comment]
番組表はGetServiceList()（EPG取得で得た全サービス情報を取得する）から映像のサービスを
検索関係はGetChDataList()（チャンネルスキャンで得たチャンネル情報のリスト）からEPG取得対象のャンネルを
なのでちょっと違った感じになります
