### ISSUE TITLE
ライブラリの表示順を更新日時にしたい

### ISSUE THREAD

**Issue by ryohei-ochi** [EMWUI/EDCB_Material_WebUI#13]
ライブラリの表示順をファイル名ではなく、更新日時にしたいと思いソースを見ていました。

まずはSessionStrageにあるXMLに更新日時を入れるため、
/api/Libraryへ、lfs.attributes(path..'\\'..fname, 'modification')を入れて、更新日時を取得しようしてますがうまく行きません。

luaは初めて触る言語なので、まだあまり理解できていませんが、アドバイスいただけませんか？

**Comment by ryohei-ochi** [comment]
すみません、自己解決しました。

フォークして公開させていただきました、ありがとうございます！
https://github.com/ryohei-ochi/EDCB_Material_WebUI

**Comment by EMWUI** [comment]
最近いじってなく対応できなくてすいません
ソート機能などはできてませんが、FindFile()からでも更新日時を取得できましたので追加しました

**Comment by ryohei-ochi** [comment]
どうもありがとうございます。
拝見させていただきます！
