### ISSUE TITLE
予約が変更できない、予約一覧が一瞬だけ表示される

### ISSUE THREAD

**Issue by EMWUI** [EMWUI/EDCB_Material_WebUI#23]
これらの事象は、古いcommon.jsで動作してる可能性が考えられます
ですのでスーパーリロードで解決出来るはずですが、解決できないようです
このことから 15bee4026263aeb2be4cffa3d4d257d65c6a36fe で追加したService Workers周りで不具合が起きた可能性が考えられます
お手数ですがサイトデータの削除を試すようお願いします
Chromeの場合はこちらから

![スクリーンショット](https://user-images.githubusercontent.com/17932815/233598676-1b34318d-4a52-473a-b2ea-47b8658cd861.png)

サイトデータの削除で解決出来ない場合以下の情報をお願いします
使用しているブラウザ、他のブラウザではどうか
http、httpsどちらでアクセスしているか
httpの場合localhostかどうか、またlocalhost以外の場合はどうか
(Service Workersはhttpsが必須でlocalhostのみ例外で動作します）

**Comment by 3rd-winter** [comment]
主に予約一覧とEPG予約の画面において操作が反映されません
・録画の有効無効を切り替えてもEpgTimer側に反映されずリロードすると元に戻る
・条件検索タブの[クリア][全選択][追加][削除][変更]等をクリックしても動作しない
・録画設定タブの[デフォルト設定で使用]のチェックを外しても各項目のグレーアウトが解除されない

当方では ac891ca795b761bc9e826bfb702d922c6f0a7e3b 以降で問題が発生し、 195dfd71499c78219d5dfb9b9347d9039ec4379d 以前であれば正常に動作するため 15bee4026263aeb2be4cffa3d4d257d65c6a36fe の影響ではないのかも知れません

環境
・Win10 Chrome、泥12 Chrome,ChromeBeta
・EDCB-work-plus-s-230325+EMWUI 7d1b21c4b766c37271e8f42253d460fd5b07d5d3
・localhost、別PCやスマホからのIPv4アドレス,FQDNでのアクセス
上記の環境でスーパーリロードおよびサイトデータ削除を実施、シークレットウィンドウでも試しましたがSSL有り無し共に当該事象が発生しました

**Comment by EMWUI** [comment]
詳しい情報ありがとうございます。
SSLありなしで変わらない、シークレットウィンドウでもならService Workersは全く関係なさそうですね
一覧が消えるというのは起こっていないでしょうか？
そうであればキャッシュが残って起きたバグと ac891ca795b761bc9e826bfb702d922c6f0a7e3b で追加されたバグとで勘違いしました
一覧が消えてたけどスーパーリロードで一覧は消えなくなったという方がいたら教えて欲しいです

サイドパネルでの操作が反映されないというだけあれば
番組の詳細や録画設定の読み込み部分で失敗してスクリプトが止まった可能性が高いのですが
有効⇔無効の切り替えも反映されないのであれば他の原因がありそうです
コンソールでエラーが出ていたら内容を教えてください
コンソールは右クリックメニューの検証（もしくはCtl+Shift+I）で見ることが出来ます

よろしくお願いいたします。

**Comment by EMWUI** [comment]
情報のおかげでバグの再現ができ原因の特定ができました
協力ありがとうございました

予約一覧が一瞬だけ表示さる原因がキャッシュ以外であった場合、修正できてないと思うので
ご報告の程よろしくお願いいたします。
