### ISSUE TITLE
番組名の「&#」＋数字の並びが文字参照として表示される

### ISSUE THREAD

**Issue by Tokman5** [EMWUI/EDCB_Material_WebUI#28]
![emwuibug](https://github.com/user-attachments/assets/142b8e3f-6d55-4096-b79d-26da4576bc4f)
画像のように、番組名に「#84&#85」のような文字列が含まれている場合、「&#85」の部分が数値文字参照と扱われてしまい、大文字のUに化けてしまいます。
番組をクリックしてポップアップする画面と、「放送中」のページでこの現象を確認しました。予約一覧のページ等、正しい表示になっている箇所もあります。
Linux上で動かしているEDCBにEMWUIを導入しており、windows+chrome、ios+safariで同じ現象が起きるのを確認しました。

**Comment by EMWUI** [comment]
お待たせしました
これで正しく表示されるかと思います
