### ISSUE TITLE
EpgTimerpluginでリモート視聴ができない

### ISSUE THREAD

**Issue by 5ym** [EMWUI/EDCB_Material_WebUI#4]
度々すみませんこちらの環境の問題かもしれませんがリモート視聴開始時にTvTestでリモート視聴で指定したチャンネルの選局は行われるのですがluaスクリプトからは404が帰ってくる状況です

**Comment by xtne6f** [comment]
割り込みすみません。EMWUIに関してTVTestやEpgTimerPluginは関係しないと思います。
(もしかしてEdcbPlugInのほうでしょうか？EdcbPlugInには"UDP/TCP送信"の機能が今のところ無いのでリモート視聴機能は使えないと思います)

**Comment by 5ym** [comment]
すみませんEdcbPluginでした理解いたしましたお手数おかけして申し訳ありません
