### ISSUE TITLE
ワンセグ同時出力とRecName_Macro併用するとファイルが二つ出力してしまう件

### ISSUE THREAD

**Issue by amkzku** [EMWUI/EDCB_Material_WebUI#9]
＝問題の様子＝
デフォルトプリセットでRecName_Macroを使ってワンセグを改名しようとすると、ワンセグが二つ出力してしまった。

＝使っている環境＝
xtne6f氏のEDCBバージョンwork-plus-s-181019をWin7・VS2015でビルドしてみた。
EMWUIのcommit cfe3926【日付2018年10月9日】までのソースコードを使っている。

＝問題の再現手順＝
①RecName_Macro.dllの副本を作る、RecName_Macro_1.dllへ改名する。
②EpgTimerの録画デフォルトプリセットで「ワンセグを別ファイルに同時出力する」をチェック。
③同じくデフォルトプリセットで「部分受信追加」をクリック、ファイル名プラグインにRecName_Macro_1.dllを選択し、設定でマクロ「$Title2$_1SEG.ts」を設定する。
④変更をクリックしてプリセットを保存する。
⑤EMWUIを立ち上げ、番組表で任意な番組をクリックしてEPG予約をする。録画設定画面ではちゃんとワンセグ改名の設定が反映している。
⑥EpgTimerの自動予約登録で追加された予約を選択し変更をクリック、ワンセグ改名の設定が二つ追加されたことを発覚。
⑦ちなみに別のEPG予約を見てみると、EPG予約を変更するたびに、改名の設定が二つ追加されることになっているようで。

＝予想の正常稼働＝
①EPG予約を追加するたび、ワンセグ改名の設定が一つだけ追加される。
②EPG予約を変更するたび、ワンセグ改名の設定が新しく追加されない。

大変素晴らしい作品にありがとうございます。
需要があまりないのかもしれませんが、対応していただけると幸いです。
何か漏れている点がありましたらご連絡ください。

**Comment by EMWUI** [comment]
遅くなりすいません。
修正いたしました

**Comment by amkzku** [comment]
問題が無事解決しました。ありがとうございました。
